import { test, expect } from '@playwright/test';

test.describe('Task 2.2: Replit Workspace Document Panel E2E Suite', () => {
  test.beforeEach(async ({ page }) => {
    // Mock SuperDocs Cloud REST API endpoints
    await page.route('https://api.superdocs.app/**', async (route) => {
      const url = route.request().url();
      const method = route.request().method();

      if (url.endsWith('/v1/sessions/init') && method === 'POST') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({ session_id: 'session_e2e_123' }),
        });
      }

      if (url.endsWith('/v1/documents/upload-base64') && method === 'POST') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            session_id: 'session_e2e_123',
            document_id: 'doc_e2e_123',
            chunks_count: 3,
            html: '<h1>SuperDocs Demo</h1><p>Initial Content</p>',
          }),
        });
      }

      if (url.endsWith('/v1/chat/async') && method === 'POST') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({ job_id: 'job_e2e_789' }),
        });
      }

      if (url.includes('/v1/jobs/job_e2e_789') && method === 'GET') {
        // Return awaiting_approval with double-JSON encoded pending_changes
        const pendingChangesPayload = {
          batch_id: 'batch_e2e_1',
          batch_total: 3,
          awaiting_kind: 'approval',
          changes: [
            {
              change_id: 'chg_1',
              operation: 'replace',
              old_html: '<h1>SuperDocs Demo</h1>',
              new_html: '<h1>SuperDocs Replit Extension</h1>',
              ai_explanation: 'Updated project title to match Replit workspace package',
            },
            {
              change_id: 'chg_2',
              operation: 'insert',
              new_html: '<h2>API Reference</h2><p>export function add(a, b)</p>',
              ai_explanation: 'Added API reference section extracted from src/index.ts',
            },
            {
              change_id: 'chg_3',
              operation: 'delete',
              old_html: '<p>Legacy unneeded note</p>',
              ai_explanation: 'Removed obsolete boilerplate notes',
            },
          ],
        };

        const doubleEncoded = JSON.stringify({
          content: JSON.stringify(pendingChangesPayload),
        });

        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            job_id: 'job_e2e_789',
            status: 'awaiting_approval',
            progress: 100,
            metadata: {
              pending_changes: doubleEncoded,
            },
          }),
        });
      }

      if (url.includes('/v1/chat/session_e2e_123/approve') && method === 'POST') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            job_id: 'job_e2e_789',
            status: 'completed',
          }),
        });
      }

      if (url.endsWith('/v1/documents/export') && method === 'POST') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            download_url: 'https://api.superdocs.app/exports/README.pdf',
            filename: 'README.pdf',
            format: 'pdf',
          }),
        });
      }

      if (url.includes('/exports/README.pdf') && method === 'GET') {
        return route.fulfill({
          status: 200,
          contentType: 'application/pdf',
          body: '%PDF-1.4 Mock Replit Export Document Generated By SuperDocs AI',
        });
      }

      if (url.includes('/v1/templates') && method === 'GET') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            templates: [
              {
                id: 'tmpl_1',
                name: 'API Spec Template',
                description: 'Standard REST and SDK API documentation structure',
                document_type: 'spec',
                default_content: '# {{project_name}} Specification\n\n## Overview\n{{description}}',
                variables: [
                  { name: 'project_name', description: 'Project Name', default_value: 'Replit App', required: true },
                  { name: 'description', description: 'Overview summary', default_value: 'Fast TypeScript service', required: false },
                ],
              },
            ],
          }),
        });
      }

      if (url.includes('/v1/prompts') && method === 'GET') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            prompts: [
              {
                id: 'prompt_1',
                name: 'Security & Auth Audit Prompt',
                description: 'Generates security overview and auth requirements',
                template: 'Document the authentication mechanics for {{module_name}}',
                variables: [
                  { name: 'module_name', description: 'Module to audit', default_value: 'AuthMiddleware', required: true },
                ],
              },
            ],
          }),
        });
      }

      if (url.includes('/versions/v1') && method === 'GET') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            version_id: 'v1',
            document_id: 'doc_e2e_123',
            created_at: '2026-08-25T11:00:00Z',
            created_by: 'Initial Ingestion',
            change_summary: 'Initial draft upload',
            html: '<h1>SuperDocs Demo</h1>',
            is_current: false,
          }),
        });
      }

      if (url.includes('/versions') && method === 'GET') {
        return route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            versions: [
              {
                version_id: 'v2',
                document_id: 'doc_e2e_123',
                created_at: '2026-08-25T12:00:00Z',
                created_by: 'SuperDocs AI',
                change_summary: 'Approved API Reference additions',
                html: '<h1>SuperDocs Replit Extension</h1><h2>API Reference</h2>',
                is_current: true,
              },
              {
                version_id: 'v1',
                document_id: 'doc_e2e_123',
                created_at: '2026-08-25T11:00:00Z',
                created_by: 'Initial Ingestion',
                change_summary: 'Initial draft upload',
                html: '<h1>SuperDocs Demo</h1>',
                is_current: false,
              },
            ],
          }),
        });
      }

      // Default fallback
      return route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ success: true }),
      });
    });
  });

  test('Complete 10-Step User Workflow: Ingest, Cherry-Pick Review, Export to Replit FS & Zero-Drift Drift', async ({ page }) => {
    // 1. Navigate to Replit Extension Host Simulator
    await page.goto('/replit-host.html');
    await page.waitForLoadState('networkidle');

    // Locate the iframe containing the extension
    const iframeElement = page.frameLocator('#ext-frame');

    // 2. Verify Handshake and Workspace Connection
    await expect(iframeElement.getByRole('heading', { name: 'SuperDocs', level: 1 })).toBeVisible({ timeout: 15000 });
    await expect(iframeElement.getByText('Replit Document Panel')).toBeVisible();

    // 3. Set API Key in Memory via Animated Modal Popover
    const setApiKeyBtn = iframeElement.getByRole('button', { name: 'Set API Key' });
    await expect(setApiKeyBtn).toBeVisible();
    await setApiKeyBtn.click();

    // Modal popup appears with dialog role
    await expect(iframeElement.getByRole('heading', { name: 'SuperDocs API Key' })).toBeVisible();
    const apiKeyInput = iframeElement.getByPlaceholder('sk_...');
    await expect(apiKeyInput).toBeVisible();
    await apiKeyInput.fill('sk_live_replit_test_key_889922');

    const saveApiKeyBtn = iframeElement.getByRole('button', { name: 'Save' });
    await saveApiKeyBtn.click();
    await expect(iframeElement.getByText('API Key Set')).toBeVisible();

    // 4. File Tree Navigation & Selection
    await expect(iframeElement.getByRole('tab', { name: 'Files' })).toBeVisible();
    await expect(iframeElement.getByText('package.json')).toBeVisible();
    await expect(iframeElement.getByText('README.md')).toBeVisible();
    await expect(iframeElement.getByText('src')).toBeVisible();

    // Select package.json by clicking its text
    await iframeElement.getByText('package.json').click();

    // 5. Navigate to Draft Tab and Configure Generation
    const draftTab = iframeElement.getByRole('tab', { name: 'Draft' });
    await draftTab.click();

    await expect(iframeElement.getByRole('heading', { name: 'Create Documentation' })).toBeVisible();
    const instructionInput = iframeElement.locator('textarea');
    await instructionInput.fill('Create comprehensive developer documentation for the Replit workspace.');

    // 6. Submit Generation
    const generateBtn = iframeElement.getByRole('button', { name: 'Generate Document' });
    await expect(generateBtn).toBeEnabled();
    await generateBtn.click();

    // 7. Automatic Transition to Review Tab & Cherry-Picking Diffs
    await expect(iframeElement.getByRole('tab', { name: /Review/i })).toBeVisible();
    await expect(iframeElement.getByText('3 Proposed Changes', { exact: true })).toBeVisible({ timeout: 10000 });
    await expect(iframeElement.getByText('3 of 3 Selected')).toBeVisible();

    // Verify Diff Operations (Replace, Insert, Delete)
    await expect(iframeElement.getByText('Replace', { exact: true })).toBeVisible();
    await expect(iframeElement.getByText('Insert', { exact: true })).toBeVisible();
    await expect(iframeElement.getByText('Delete', { exact: true })).toBeVisible();
    await expect(iframeElement.getByText('Added API reference section extracted from src/index.ts')).toBeVisible();

    // Test Cherry-Picking: Deselect All, then Select only Change #1 and #2
    const deselectAllBtn = iframeElement.getByRole('button', { name: 'Deselect All' });
    await deselectAllBtn.click();
    await expect(iframeElement.getByText('0 of 3 Selected')).toBeVisible();

    // Toggle Change #1 and Change #2
    await iframeElement.locator('#change-chg_1').check();
    await iframeElement.locator('#change-chg_2').check();
    await expect(iframeElement.getByText('2 of 3 Selected')).toBeVisible();

    // 8. Approve Selected Changes
    const approveBtn = iframeElement.getByRole('button', { name: /Approve 2 selected changes/i });
    await approveBtn.click();

    await expect(iframeElement.getByText('Document generation complete')).toBeVisible({ timeout: 10000 });

    // 9. Export to Replit Filesystem
    const exportTab = iframeElement.getByRole('tab', { name: 'Export' });
    await exportTab.click();

    await expect(iframeElement.getByRole('heading', { name: 'Export Document' })).toBeVisible();
    const destinationInput = iframeElement.getByPlaceholder('e.g., docs/README.pdf');
    await expect(destinationInput).toHaveValue('docs/README.pdf');

    const exportBtn = iframeElement.getByRole('button', { name: /Export & Save/i });
    await exportBtn.click();

    // Verify file written message
    await expect(iframeElement.getByText(/Successfully exported PDF to docs\/README\.pdf/i)).toBeVisible({ timeout: 10000 });

    // 10. Verify File Actually Persisted to Host Filesystem
    const writtenFiles = await page.evaluate(() => {
      const map = (window as any).__writtenFiles;
      return Array.from(map.keys());
    });
    expect(writtenFiles).toContain('docs/README.pdf');
  });

  test('UI/UX: Theme Switcher & Side Drawer Interactions Flow', async ({ page }) => {
    await page.goto('/replit-host.html');
    await page.waitForLoadState('networkidle');

    const iframeElement = page.frameLocator('#ext-frame');
    await expect(iframeElement.getByRole('heading', { name: 'SuperDocs', level: 1 })).toBeVisible({ timeout: 15000 });

    // 1. Test Theme Toggle (Dark -> Light -> Dark)
    const themeBtn = iframeElement.getByLabel('Toggle Theme');
    await expect(themeBtn).toBeVisible();
    await themeBtn.click(); // Switch to light
    await themeBtn.click(); // Switch back to dark

    // 2. Test Side Drawer Toggle
    const drawerBtn = iframeElement.getByLabel('Toggle Side Drawer');
    await expect(drawerBtn).toBeVisible();
    await drawerBtn.click();

    // Drawer opens showing Workspace Overview
    await expect(iframeElement.getByText('Workspace Overview')).toBeVisible();
    await expect(iframeElement.getByText('Zero-Drift Status')).toBeVisible();

    // Close drawer via close button inside drawer
    const closeDrawerBtn = iframeElement.getByLabel('Close Drawer');
    await expect(closeDrawerBtn).toBeVisible();
    await closeDrawerBtn.click();
    await expect(iframeElement.getByText('Workspace Overview')).not.toBeVisible();
  });

  test('Templates Gallery & Dynamic Variable Injection Flow', async ({ page }) => {
    await page.goto('/replit-host.html');
    await page.waitForLoadState('networkidle');

    const iframeElement = page.frameLocator('#ext-frame');
    await expect(iframeElement.getByRole('heading', { name: 'SuperDocs', level: 1 })).toBeVisible({ timeout: 15000 });

    // Set API Key
    await iframeElement.getByRole('button', { name: 'Set API Key' }).click();
    await iframeElement.getByPlaceholder('sk_...').fill('sk_test_tmpl_key');
    await iframeElement.getByRole('button', { name: 'Save' }).click();

    // Open Templates Tab
    const templatesTab = iframeElement.getByRole('tab', { name: 'Templates' });
    await templatesTab.click();

    // Verify Templates & Prompts loaded
    await expect(iframeElement.getByText('API Spec Template')).toBeVisible({ timeout: 10000 });
    await expect(iframeElement.getByText('Security & Auth Audit Prompt')).toBeVisible();

    // Click template card to select it
    await iframeElement.getByText('API Spec Template').click();

    // Verify Variable inputs rendered
    await expect(iframeElement.getByText('Fill in the template variables below')).toBeVisible();
    const projNameInput = iframeElement.locator('input[placeholder="Project Name"]');
    await projNameInput.fill('CloudBillingEngine');

    // Apply Template -> Triggers generation and redirects to Review
    const applyBtn = iframeElement.getByRole('button', { name: 'Apply Template' });
    await applyBtn.click();

    await expect(iframeElement.getByRole('tab', { name: /Review/i })).toBeVisible();
    await expect(iframeElement.getByText('3 Proposed Changes', { exact: true })).toBeVisible({ timeout: 10000 });
  });

  test('Version History Tab & Snapshot Rollback Preview', async ({ page }) => {
    await page.goto('/replit-host.html');
    await page.waitForLoadState('networkidle');

    const iframeElement = page.frameLocator('#ext-frame');
    await expect(iframeElement.getByRole('heading', { name: 'SuperDocs', level: 1 })).toBeVisible({ timeout: 15000 });

    // Set API Key
    await iframeElement.getByRole('button', { name: 'Set API Key' }).click();
    await iframeElement.getByPlaceholder('sk_...').fill('sk_test_history_key');
    await iframeElement.getByRole('button', { name: 'Save' }).click();

    // Select file in FileTree
    await iframeElement.getByText('package.json').click();

    // First generate to acquire documentId
    await iframeElement.getByRole('tab', { name: 'Draft' }).click();
    await iframeElement.getByRole('button', { name: 'Generate Document' }).click();
    await expect(iframeElement.getByText('3 Proposed Changes', { exact: true })).toBeVisible({ timeout: 10000 });

    // Switch to History Tab
    const historyTab = iframeElement.getByRole('tab', { name: 'History' });
    await historyTab.click();

    // Verify Snapshot list rendered
    await expect(iframeElement.getByText('v2')).toBeVisible({ timeout: 10000 });
    await expect(iframeElement.getByText('v1')).toBeVisible();
    await expect(iframeElement.getByText('Approved API Reference additions')).toBeVisible();

    // Click Preview button on v1
    const previewBtn = iframeElement.getByRole('button', { name: 'Preview' }).last();
    await previewBtn.click();

    // Verify HTML Preview is visible
    await expect(iframeElement.getByText('HTML Preview')).toBeVisible();
    await expect(iframeElement.getByRole('button', { name: 'Revert' })).toBeVisible();
  });
});
